version: 2
updates:

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: '00:00'
    timezone: "America/Denver"
  open-pull-requests-limit: 10
  commit-message:
      prefix: "chore"
      include: "scope"
